### ISSUE TITLE
SpeciesTreeDistanceLogger confused by different taxon orderings

### ISSUE THREAD

**Issue by rbouckaert** [rbouckaert/Babel#11]
When  gene trees have different taxon orderings, SpeciesTreeDistanceLogger appears to get confused and produces incorrect output. When only a single gene tree is used, everything is fine.

**Comment by cinthylorein** [comment]
I am attempting to compare a species tree with 100 gene trees. The species tree has 108 taxa, and the labels are different from those in the gene trees. For the gene trees, I have loci between 90 and 108 taxa. I am using a map file with two columns, where the first column contains the labels for the gene trees and the second column contains the labels for the species tree. However, when I try to compare more than one gene tree, I receive the following error message: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at beastfx.app.tools.AppLauncher.runAppFromCMD(Unknown Source)
	at beastfx.app.tools.AppLauncher.main(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at beast.pkgmgmt.launcher.BeastLauncher.run(Unknown Source)
	at beast.pkgmgmt.launcher.AppLauncherLauncher.main(Unknown Source)
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "java.util.Map.get(Object)" is null
	at beastlabs.evolution.tree.RNNIMetric.mrca(Unknown Source)
	at beastlabs.evolution.tree.RNNIMetric.distance(Unknown Source)
	at beastlabs.evolution.tree.RNNIMetric.distance(Unknown Source)
	at babel.tools.SpeciesTreeDistanceLogger.processTree(Unknown Source)
	at babel.tools.SpeciesTreeDistanceLogger.run(Unknown Source)
	at beastfx.app.tools.Application.<init>(Unknown Source)
	at beastfx.app.tools.Application.<init>(Unknown Source)
	at beastfx.app.tools.Application.<init>(Unknown Source)
	at babel.tools.SpeciesTreeDistanceLogger.main(Unknown Source) 

The error is caused by a NullPointerException, which is thrown when the method "java.lang.Integer.intValue()" is called on a null value returned by "java.util.Map.get(Object)".It is unclear whether the error is due to the presence of loci with less than 108 taxa or a different order.
