### ISSUE TITLE
Unable to use SDollo template

### ISSUE THREAD

**Issue by SimonGreenhill** [rbouckaert/Babel#2]
Beauti gives this error:

```
beast.util.XMLParserException:
Error 1017 parsing the xml input file

nullClass could not be found. Did you mean beast.evolution.substitutionmodel.MutationDeathModel?

Error detected about here:
  <beast>
      <alignment id='orgdata.utoaztecan' spec='beast.evolution.alignment.FilteredAlignment'>
          <userDataType spec='beast.evolution.datatype.MutationDeathType'>

    at beast.util.XMLParser.createObject(Unknown Source)
    at beast.util.XMLParser.parseInputs(Unknown Source)
    at beast.util.XMLParser.createObject(Unknown Source)
    at beast.util.XMLParser.parseTemplate(Unknown Source)
    at beast.app.beauti.BeautiSubTemplate.createSubNet(Unknown Source)
    at beast.app.beauti.BeautiSubTemplate.createSubNet(Unknown Source)
    at beast.app.beauti.BeautiDoc.addAlignmentWithSubnet(Unknown Source)
    at beast.app.beauti.BeautiAlignmentProvider.addAlignments(Unknown Source)
    at beast.app.beauti.BeautiAlignmentProvider.getAlignments(Unknown Source)
    at beast.app.beauti.BeautiAlignmentProvider.getAlignments(Unknown Source)
    at beast.app.beauti.Beauti$1.actionPerformed(Unknown Source)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
    at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
    at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
    at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
    at com.apple.laf.AquaMenuItemUI.doClick(AquaMenuItemUI.java:157)
    at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
    at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
    at java.awt.Component.processMouseEvent(Component.java:6525)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3322)
    at java.awt.Component.processEvent(Component.java:6290)
    at java.awt.Container.processEvent(Container.java:2234)
    at java.awt.Component.dispatchEventImpl(Component.java:4881)
    at java.awt.Container.dispatchEventImpl(Container.java:2292)
    at java.awt.Component.dispatchEvent(Component.java:4703)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
    at java.awt.Container.dispatchEventImpl(Container.java:2278)
    at java.awt.Window.dispatchEventImpl(Window.java:2739)
    at java.awt.Component.dispatchEvent(Component.java:4703)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:751)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:702)
    at java.awt.EventQueue$3.run(EventQueue.java:696)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.awt.EventQueue$4.run(EventQueue.java:724)
    at java.awt.EventQueue$4.run(EventQueue.java:722)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:721)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
PARTITIONS0:

[[], [], []]
InPosterior=posterior prior likelihood
Could not find beastObject with id treeLikelihood.Species. Typo in template perhaps?

PARTITIONS0:

[[], [], []]
PARTITIONS0:

[[], [], []]
PARTITIONS0:

[[], [], []]
PARTITIONS0:

[[], [], []]
Validation message: At least one input of name 'xx' must be specified.
PARTITIONS0:

[[], [], []]
class beast.core.MCMC != class beast.core.Runnable
PARTITIONS0:

[[], [], []]
Validation message: At least one input of name 'xx' must be specified.
class beast.core.MCMC != class beast.core.Runnable
```

**Comment by rbouckaert** [comment]
Do you have the Babel package installed?
You can download https://github.com/rbouckaert/Babel/releases/download/0.0.1/Babel.addon.v0.1.0.zip
and unzip it in the BEAST 2.4 directory. Make sure it is in its own Babel subdirectory, so create
~/Library/Application\ Support/BEAST/2.4/Babel first, copy Babel.addon.v0.1.0.zip to this directory and then
unzip Babel.addon.v0.1.0.zip
should do the trick.

**Comment by SimonGreenhill** [comment]
Yep that works. Any chance of getting Babel into the BEAUTi Appstore?
